version: '3'
services:
    node-express:
        build: ./node-express
        container_name: "node-express"
        depends_on:
            - rabbitmq-server
        ports:
            - "5000:5000"
        volumes:
            - ./node-express:/usr/src/app
            - /usr/src/app/node-express
        command: bash -c "npm ci && npm run start-watch"

    rabbitmq-server:
        image: rabbitmq:3.8.2
        container_name: "rabbitmq-server"
        environment:
            - RABBITMQ_DEFAULT_USER=guest
            - RABBITMQ_DEFAULT_PASS=guest
        ports:
            - "15672:15672"
            - "15692:15692"
            - "5672:5672"
        volumes:
            - ./conf/rabbitmq_enabled_plugins:/etc/rabbitmq/enabled_plugins

    nginx:
        build: ./nginx
        container_name: "nginx"
        depends_on:
            - node-express
        ports:
            - "8080:80"

    nginx_exporter:
        image: nginx/nginx-prometheus-exporter:0.4.2
        container_name: "nginx-exporter"
        ports:
            - "9113:9113"
        environment:
            - SCRAPE_URI=http://nginx/metrics
            - TELEMETRY_PATH=/prometheus_nginx
            - NGINX_RETRIES=10