version: '3'
services:
  rabbitmq_exporter:
    image: kbudde/rabbitmq-exporter
    container_name: "rabbitmq-exporter"
    ports:
      - "9999:9090"
    environment:
      RABBIT_URL: "http://rabbitmq:15672"
      RABBIT_USER: "guest"
      RABBIT_PASSWORD: "guest"
      PUBLISH_PORT: "9090"
      OUTPUT_FORMAT: "JSON"
      LOG_LEVEL: "debug"

  nginx_exporter:
    image: nginx/nginx-prometheus-exporter:0.4.2
    container_name: "nginx-exporter"
    ports:
      - "9113:9113"
    environment:
      SCRAPE_URI: http://nginx:3002/metrics
      TELEMETRY_PATH: /prometheus
      NGINX_RETRIES: 10
      
  prometheus:
    image: prom/prometheus:v1.4.1
    ports:
      - "9090:9090"
    volumes:
      - ./conf/prometheus.yml:/etc/prometheus/prometheus.yml
    depends_on:
      - rabbitmq_exporter

  grafana:
    image: grafana/grafana
    ports:
      - "3300:3000"
    depends_on:
      - prometheus