version: '3'
services:
    rabbitmq:
      image: rabbitmq:3-management
      container_name: "rabbitmq"
      environment:
        - RABBITMQ_DEFAULT_USER=guest
        - RABBITMQ_DEFAULT_PASS=guest
      ports:
        - "15672:15672"
        - "5672:5672"
    node-express:
        build: ./node-express
        container_name: "node"
        ports:
            - "5000:5000"
    nginx:
        build: ./nginx
        container_name: "nginx"
        depends_on:
            - node-express
        ports:
            - "80:80"