global:
  scrape_interval: 30s
  scrape_timeout: 10s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']
  - job_name: 'rabbitmq-job'
    scrape_interval: 10s
    static_configs:
      - targets: ['rabbitmq-server:15692']
  - job_name: 'nginx-job'
    scrape_interval: 10s
    metrics_path: '/prometheus_nginx'
    static_configs:
      - targets: ['nginx-exporter:9113']
  - job_name: 'node-express'
    scrape_interval: 5s
    metrics_path: '/metrics'
    static_configs:
      - targets: ['node-express:5000']